(define (domain crobber)
  (:requirements :typing :strips :conditional-effects)
  (:types location)
  (:constants c11 c12 c13 c21 c22 c23 - location)
  (:predicates (white-in ?loc - location)
	       (black-in ?loc - location)
	       (road ?from - location ?to - location)
	       )
  (:action clob
    :parameters (?from - location ?to - location)
    :precondition (and (white-in ?from) (road ?from ?to) (black-in ?to))
    :effect (and (not (white-in ?from)) (white-in ?from) (not (black-in ?to))
		 (oneof (when (and (black-in c11) (white-in c12)) (and (black-in c12) (not (black-in c11)) (not (white-in c12))))
				(when (and (black-in c11) (white-in c21)) (and (black-in c21) (not (black-in c11)) (not (white-in c21))))
				(when (and (black-in c12) (white-in c13)) (and (black-in c13) (not (black-in c12)) (not (white-in c13))))
				(when (and (black-in c12) (white-in c22)) (and (black-in c22) (not (black-in c12)) (not (white-in c22))))
				(when (and (black-in c12) (white-in c11)) (and (black-in c11) (not (black-in c12)) (not (white-in c11))))
				(when (and (black-in c22) (white-in c23)) (and (black-in c23) (not (black-in c22)) (not (white-in c23))))
				(when (and (black-in c22) (white-in c12)) (and (black-in c12) (not (black-in c22)) (not (white-in c12))))
				(when (and (black-in c22) (white-in c21)) (and (black-in c21) (not (black-in c22)) (not (white-in c21))))
				(when (and (black-in c13) (white-in c12)) (and (black-in c12) (not (black-in c13)) (not (white-in c12))))
				(when (and (black-in c13) (white-in c23)) (and (black-in c23) (not (black-in c13)) (not (white-in c23))))
				(when (and (black-in c23) (white-in c22)) (and (black-in c22) (not (black-in c23)) (not (white-in c22))))
				(when (and (black-in c23) (white-in c13)) (and (black-in c13) (not (black-in c23)) (not (white-in c13))))
				(when (and (black-in c21) (white-in c22)) (and (black-in c22) (not (black-in c21)) (not (white-in c22))))
				(when (and (black-in c21) (white-in c11)) (and (black-in c11) (not (black-in c21)) (not (white-in c11))))
		 )))
)
